CREATE TABLE "Rating" (
  "rating_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "Films" (
  "film_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar,
  "releaseDate" date,
  "duration" integer,
  "rating_id" integer REFERENCES Rating (rating_id) ON DELETE CASCADE
);

CREATE TABLE "Genres" (
  "genre_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "Films_genre" (
  "film_id" integer REFERENCES Films (film_id) ON DELETE CASCADE,
  "genre_id" integer REFERENCES Genres (genre_id) ON DELETE CASCADE
);

CREATE TABLE "Users" (
  "user_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar,
  "login" varchar NOT NULL,
  "email" varchar,
  "birthday" date
);

CREATE TABLE "Friendship" (
  "user1_id" integer REFERENCES Users (user_id) ON DELETE CASCADE,
  "user2_id" integer REFERENCES Users (user_id) ON DELETE CASCADE,
  "user1_authorized" bool NOT NULL DEFAULT false,
  "user2_authorized" bool NOT NULL DEFAULT false,
);

CREATE TABLE "Like" (
  "user_id" integer REFERENCES Users (user_id) ON DELETE CASCADE,
  "film_id" integer REFERENCES Films (film_id) ON DELETE CASCADE,
);
