CREATE TABLE IF NOT EXISTS ratings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  description varchar,
  releaseDate date,
  duration integer NOT NULL CHECK (duration > 0),
  rating_id bigint REFERENCES ratings (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genres (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS films_genre (
  film_id bigint REFERENCES films (id) ON DELETE CASCADE NOT NULL,
  genre_id bigint REFERENCES genres (id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  last_name varchar,
  login varchar UNIQUE NOT NULL,
  email varchar UNIQUE,
  birthday date
);

CREATE TABLE IF NOT EXISTS friendship (
  source_id bigint REFERENCES users (id) ON DELETE CASCADE NOT NULL,
  destination_id bigint REFERENCES users (id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (source_id, destination_id)
);

CREATE TABLE IF NOT EXISTS likes (
  user_id bigint REFERENCES users (id) ON DELETE CASCADE NOT NULL,
  film_id bigint REFERENCES films (id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (user_id, film_id)
);
